### ISSUE TITLE
Assist Microphone - Failed to start add-on

### ISSUE THREAD

**Issue by xvlw** [rhasspy/hassio-addons#27]
Hello

I installed the Assist Microphone to utilize my Jabra Speak 410 to test out the new updates.

However when I go to start the add-on I get the below error.

I have rebooted the device that Home Assistant is on a few times without success.

Is it possible to resolve this?

```
Logger: homeassistant.components.hassio
Source: components/hassio/websocket_api.py:138
Integration: Home Assistant Supervisor (documentation, issues)
First occurred: October 12, 2023 at 9:32:03 PM (9 occurrences)
Last logged: 8:44:14 AM

Failed to to call /addons/47701997_assist_microphone/start - Image 47701997/amd64-addon-assist_microphone:1.2.1 does not exist for addon_47701997_assist_microphone
```

My Config Page is below.

![8DEVown](https://github.com/rhasspy/hassio-addons/assets/85139690/ba53d4d7-8fb1-47c3-ae78-9e6c384acdaf)
![0qxoOMs](https://github.com/rhasspy/hassio-addons/assets/85139690/80d903a2-69b8-447b-a967-4cebb8d09278)
![r7kUo5m](https://github.com/rhasspy/hassio-addons/assets/85139690/0a3c54b3-0419-465b-b923-7456cffe8e7e)

**Comment by synesthesiam** [comment]
It looks like the add-on may have failed to build. I just pushed an update, so let me know if you see this again after upgrading.

**Comment by xvlw** [comment]
The update allowed the add-on to start

Thank you!

**Comment by xvlw** [comment]
Just realized, after starting the add-on, it isn't being auto discovered by Wyoming under the Integration page.

![XCTEipN](https://github.com/rhasspy/hassio-addons/assets/85139690/9487cc89-2a13-4da2-afa1-2cc9e283036e)
![l7ywqVS](https://github.com/rhasspy/hassio-addons/assets/85139690/1907c0fa-eb73-46a1-8bca-14a61c0dff7f)

**Comment by xvlw** [comment]
Here are the logs for when I try to start Assist Microphone

```
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service assist_microphone: starting
s6-rc: info: service assist_microphone successfully started
s6-rc: info: service legacy-services: starting
s6-rc: info: service legacy-services successfully started
2023-10-13 15:12:36.056092304 [W:onnxruntime:, graph.cc:3553 CleanUnusedInitializersAndNodeArgs] Removing initializer '131'. It is not used by any node and should be removed from the model.
2023-10-13 15:12:36.056198306 [W:onnxruntime:, graph.cc:3553 CleanUnusedInitializersAndNodeArgs] Removing initializer '136'. It is not used by any node and should be removed from the model.
2023-10-13 15:12:36.056222613 [W:onnxruntime:, graph.cc:3553 CleanUnusedInitializersAndNodeArgs] Removing initializer '139'. It is not used by any node and should be removed from the model.
2023-10-13 15:12:36.056247128 [W:onnxruntime:, graph.cc:3553 CleanUnusedInitializersAndNodeArgs] Removing initializer '140'. It is not used by any node and should be removed from the model.
2023-10-13 15:12:36.056273755 [W:onnxruntime:, graph.cc:3553 CleanUnusedInitializersAndNodeArgs] Removing initializer '134'. It is not used by any node and should be removed from the model.
2023-10-13 15:12:36.056591107 [W:onnxruntime:, graph.cc:3553 CleanUnusedInitializersAndNodeArgs] Removing initializer '628'. It is not used by any node and should be removed from the model.
2023-10-13 15:12:36.056624336 [W:onnxruntime:, graph.cc:3553 CleanUnusedInitializersAndNodeArgs] Removing initializer '623'. It is not used by any node and should be removed from the model.
2023-10-13 15:12:36.056650084 [W:onnxruntime:, graph.cc:3553 CleanUnusedInitializersAndNodeArgs] Removing initializer '629'. It is not used by any node and should be removed from the model.
2023-10-13 15:12:36.056672730 [W:onnxruntime:, graph.cc:3553 CleanUnusedInitializersAndNodeArgs] Removing initializer '620'. It is not used by any node and should be removed from the model.
2023-10-13 15:12:36.056697392 [W:onnxruntime:, graph.cc:3553 CleanUnusedInitializersAndNodeArgs] Removing initializer '625'. It is not used by any node and should be removed from the model.
Recording raw data 'stdin' : Signed 16 bit Little Endian, Rate 16000 Hz, Mono
ERROR:__main__:Unexpected error
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/dist-packages/homeassistant_satellite/__main__.py", line 200, in main
    async for _timestamp, event_type, event_data in stream(
  File "/usr/local/lib/python3.11/dist-packages/homeassistant_satellite/remote.py", line 28, in stream
    async with session.ws_connect(url) as websocket:
  File "/usr/local/lib/python3.11/dist-packages/aiohttp/client.py", line 1141, in __aenter__
    self._resp = await self._coro
                 ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/aiohttp/client.py", line 779, in _ws_connect
    resp = await self.request(
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/aiohttp/client.py", line 560, in _request
    await resp.start(conn)
  File "/usr/local/lib/python3.11/dist-packages/aiohttp/client_reqrep.py", line 899, in start
    message, payload = await protocol.read()  # type: ignore[union-attr]
                       ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/aiohttp/streams.py", line 616, in read
    await self._waiter
aiohttp.client_exceptions.ServerDisconnectedError: Server disconnected
```

**Comment by synesthesiam** [comment]
I've heard several reports of problems with the Jabra mics. The HA team is looking into it, but it may be necessary to try a different mic.
