### ISSUE TITLE
Assist Microphone fails to start if different hostname is used

### ISSUE THREAD

**Issue by rocket-plane** [rhasspy/hassio-addons#47]
Im using Assist Microphone version: 2.2.3. 
I have activated SSL for my homeassistant instance with
```
http:
  server_port: 443
  ssl_certificate: /ssl/fullchain.pem
  ssl_key: /ssl/privkey.pem
```
The domain I use for it is home.my_domain.de. But if I try to start the addon I get the following message:
```
File "/usr/local/lib/python3.11/dist-packages/aiohttp/connector.py", line 982, in _wrap_create_connection
  raise ClientConnectorCertificateError(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorCertificateError: Cannot connect to host homeassistant:443 ssl:True [SSLCertVerificationError: (1, "[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'homeassistant'. (_ssl.c:992)")]
ERROR:__main__:Unexpected error
Traceback (most recent call last):
File "/usr/local/lib/python3.11/dist-packages/aiohttp/connector.py", line 980, in _wrap_create_connection
  return await self._loop.create_connection(*args, **kwargs)  # type: ignore[return-value]  # noqa
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/lib/python3.11/asyncio/base_events.py", line 1112, in create_connection
  transport, protocol = await self._create_connection_transport(
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/lib/python3.11/asyncio/base_events.py", line 1145, in _create_connection_transport
  await waiter
File "/usr/lib/python3.11/asyncio/sslproto.py", line 574, in _on_handshake_complete
  raise handshake_exc
File "/usr/lib/python3.11/asyncio/sslproto.py", line 556, in _do_handshake
  self._sslobj.do_handshake()
File "/usr/lib/python3.11/ssl.py", line 979, in do_handshake
  self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'homeassistant'. (_ssl.c:992)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
File "/usr/local/lib/python3.11/dist-packages/homeassistant_satellite/__main__.py", line 200, in main
  async for _timestamp, event_type, event_data in stream(
File "/usr/local/lib/python3.11/dist-packages/homeassistant_satellite/remote.py", line 28, in stream
  async with session.ws_connect(url) as websocket:
File "/usr/local/lib/python3.11/dist-packages/aiohttp/client.py", line 1141, in __aenter__
  self._resp = await self._coro
               ^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/dist-packages/aiohttp/client.py", line 779, in _ws_connect
  resp = await self.request(
         ^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/dist-packages/aiohttp/client.py", line 536, in _request
  conn = await self._connector.connect(
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/dist-packages/aiohttp/connector.py", line 540, in connect
  proto = await self._create_connection(req, traces, timeout)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/dist-packages/aiohttp/connector.py", line 901, in _create_connection
  _, proto = await self._create_direct_connection(req, traces, timeout)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/dist-packages/aiohttp/connector.py", line 1206, in _create_direct_connection
  raise last_exc
File "/usr/local/lib/python3.11/dist-packages/aiohttp/connector.py", line 1175, in _create_direct_connection
  transp, proto = await self._wrap_create_connection(
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/dist-packages/aiohttp/connector.py", line 982, in _wrap_create_connection
  raise ClientConnectorCertificateError(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorCertificateError: Cannot connect to host homeassistant:443 ssl:True [SSLCertVerificationError: (1, "[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'homeassistant'. (_ssl.c:992)")]
ERROR:__main__:Unexpected error
Traceback (most recent call last):
File "/usr/local/lib/python3.11/dist-packages/aiohttp/connector.py", line 980, in _wrap_create_connection
  return await self._loop.create_connection(*args, **kwargs)  # type: ignore[return-value]  # noqa
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/lib/python3.11/asyncio/base_events.py", line 1112, in create_connection
  transport, protocol = await self._create_connection_transport(
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/lib/python3.11/asyncio/base_events.py", line 1145, in _create_connection_transport
  await waiter
File "/usr/lib/python3.11/asyncio/sslproto.py", line 574, in _on_handshake_complete
  raise handshake_exc
File "/usr/lib/python3.11/asyncio/sslproto.py", line 556, in _do_handshake
  self._sslobj.do_handshake()
File "/usr/lib/python3.11/ssl.py", line 979, in do_handshake
  self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'homeassistant'. (_ssl.c:992)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
File "/usr/local/lib/python3.11/dist-packages/homeassistant_satellite/__main__.py", line 200, in main
  async for _timestamp, event_type, event_data in stream(
File "/usr/local/lib/python3.11/dist-packages/homeassistant_satellite/remote.py", line 28, in stream
  async with session.ws_connect(url) as websocket:
File "/usr/local/lib/python3.11/dist-packages/aiohttp/client.py", line 1141, in __aenter__
  self._resp = await self._coro
               ^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/dist-packages/aiohttp/client.py", line 779, in _ws_connect
  resp = await self.request(
         ^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/dist-packages/aiohttp/client.py", line 536, in _request
  conn = await self._connector.connect(
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/dist-packages/aiohttp/connector.py", line 540, in connect
  proto = await self._create_connection(req, traces, timeout)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/dist-packages/aiohttp/connector.py", line 901, in _create_connection
  _, proto = await self._create_direct_connection(req, traces, timeout)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/dist-packages/aiohttp/connector.py", line 1206, in _create_direct_connection
  raise last_exc
File "/usr/local/lib/python3.11/dist-packages/aiohttp/connector.py", line 1175, in _create_direct_connection
  transp, proto = await self._wrap_create_connection(
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/dist-packages/aiohttp/connector.py", line 982, in _wrap_create_connection
  raise ClientConnectorCertificateError(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorCertificateError: Cannot connect to host homeassistant:443 ssl:True [SSLCertVerificationError: (1, "[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'homeassistant'. (_ssl.c:992)")]
ERROR:__main__:Unexpected error
Traceback (most recent call last):
File "/usr/local/lib/python3.11/dist-packages/aiohttp/connector.py", line 980, in _wrap_create_connection
  return await self._loop.create_connection(*args, **kwargs)  # type: ignore[return-value]  # noqa
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/lib/python3.11/asyncio/base_events.py", line 1112, in create_connection
  transport, protocol = await self._create_connection_transport(
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/lib/python3.11/asyncio/base_events.py", line 1145, in _create_connection_transport
  await waiter
File "/usr/lib/python3.11/asyncio/sslproto.py", line 574, in _on_handshake_complete
  raise handshake_exc
File "/usr/lib/python3.11/asyncio/sslproto.py", line 556, in _do_handshake
  self._sslobj.do_handshake()
File "/usr/lib/python3.11/ssl.py", line 979, in do_handshake
  self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'homeassistant'. (_ssl.c:992)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
File "/usr/local/lib/python3.11/dist-packages/homeassistant_satellite/__main__.py", line 200, in main
  async for _timestamp, event_type, event_data in stream(
File "/usr/local/lib/python3.11/dist-packages/homeassistant_satellite/remote.py", line 28, in stream
  async with session.ws_connect(url) as websocket:
File "/usr/local/lib/python3.11/dist-packages/aiohttp/client.py", line 1141, in __aenter__
  self._resp = await self._coro
               ^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/dist-packages/aiohttp/client.py", line 779, in _ws_connect
  resp = await self.request(
         ^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/dist-packages/aiohttp/client.py", line 536, in _request
  conn = await self._connector.connect(
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/dist-packages/aiohttp/connector.py", line 540, in connect
  proto = await self._create_connection(req, traces, timeout)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/dist-packages/aiohttp/connector.py", line 901, in _create_connection
  _, proto = await self._create_direct_connection(req, traces, timeout)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/dist-packages/aiohttp/connector.py", line 1206, in _create_direct_connection
  raise last_exc
File "/usr/local/lib/python3.11/dist-packages/aiohttp/connector.py", line 1175, in _create_direct_connection
  transp, proto = await self._wrap_create_connection(
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/dist-packages/aiohttp/connector.py", line 982, in _wrap_create_connection
  raise ClientConnectorCertificateError(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorCertificateError: Cannot connect to host homeassistant:443 ssl:True [SSLCertVerificationError: (1, "[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'homeassistant'. (_ssl.c:992)")]
```
under home.my_domain.de/config/network I have entered the correct domain.

**Comment by eavyon** [comment]
Same issue here. selfsigned certificate which this addon doesnt accept. When will this addon change to binary proxy to connect as I read elsewhere? The supervisor supports it from 2023.10.1 right?

**Comment by synesthesiam** [comment]
The websocket connection is no longer needed in the official Assist Microphone add-on: https://github.com/home-assistant/addons/tree/master/assist_microphone
